### ISSUE TITLE
Lower setuptools requirement (currently >=61)

### ISSUE THREAD

**Issue by kimheino** [penguinpee/PyMunin3#4]
From munin irc:

```
12:18        bcg | Penguinpee: Interesting. Any plans for rhel9 rpm?
12:25 Penguinpee | Do you happen to know the version of setuptools shipped in el9? I have to hit the road. I can try doing a scratch build
                 | later on to find out if the version of setuptools is new enough. It needs to be >=61.
12:28        bcg | python3-setuptools-53.0.0-10.el9.noarch
12:32        bcg | PyMunin3 looks nice and I might use that for my plugins, but rhel9 support is mandatory for me.
```

If that matters, I'm the maintainer of munin.rpm in EPEL and Fedora. I've also written 10+ plugins for it in Python.

**Comment by penguinpee** [comment]
Besides RHEL9 this also applies to the current releases of Fedora:

F35: 57.4.0
F36: 59.6.0

Only F37 (62.6.0), currently in beta, has new enough setuptools to support building this package.

So, lowering the requirements will make PyMunin3 available for a broader audience.

For the nitty gritty: https://setuptools.pypa.io/en/latest/history.html#id184 (short) or [#3067](https://github.com/pypa/setuptools/issues/3067) (long).

**Comment by penguinpee** [comment]
I've lowered the setuptools requirement, just to hit another roadblock: setuptools_scm.

The requirement is `setuptools_scm[toml]>=6.2`, which is only met in f36. In f35 it's 6.0.1, but since f35 will be retired soon, I can't be bothered. For el9 setuptools_scm has not been released at all it seems: https://src.fedoraproject.org/rpms/python-setuptools_scm. I suppose I could nudge @hroncok :snake: as to why.

For a preview see: https://copr.fedorainfracloud.org/coprs/gui1ty/PyMunin3/build/4881892/

For anyone who lives by the motto _Who says I can't_, the only runtime requirement is a recent Python3 version (>=3.7). That means a local install should work without problems:

```
sudo dnf localinstall python3-PyMunin3-3.0.2-1.fc36.noarch.rpm
```

**Disclaimer:** YMMV!

**Comment by hroncok** [comment]
> The requirement is `setuptools_scm[toml]>=6.2`, which is only met in f36. In f35 it's 6.0.1, but since f35 will be retired soon, I can't be bothered. For el9 setuptools_scm has not been released at all it seems: https://src.fedoraproject.org/rpms/python-setuptools_scm. I suppose I could nudge @hroncok snake as to why.

RHEL 9 CRB repository (available and required for EPEL 9) contains python3-setuptools_scm, however also version 6.0.1.


As with the setuptools 62+ requirement, I see 2 options:

 - use the new and fancy stuff
 - build in old stable environments

You cannot have both at the same time. Either don't use the new stuff upstream or patch it out downstream in EL 9. Sorry about that.

You may of course open a RHEL Bugzilla to request the features of setuptools and setuptools_scm you want, but without a customer ticket, there is no guarantee it will be aded.

**Comment by penguinpee** [comment]
Roadblock has been cleared. Next release will be available for all current Fedora releases as well as el9. For the impatient:

https://copr.fedorainfracloud.org/coprs/gui1ty/PyMunin3/
